include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # 사용하지 않는 import → 에러
    unused_import: error
    # 사용하지 않는 지역 변수 → 경고
    unused_local_variable: warning
    # 사용하지 않는 필드 → 경고
    unused_field: warning

  exclude:
    # 생성된 파일 제외 (freezed, riverpod 등)
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/generated/**"

  language:
    # strict 모드 활성화
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # === 필수 규칙 ===
    # const 사용 권장
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true

    # 타입 명시
    always_declare_return_types: true
    always_specify_types: false  # 추론 가능할 때는 생략 허용

    # print 사용 금지 (릴리즈에서 문제)
    avoid_print: true

    # === 코드 스타일 ===
    # 빈 else 금지
    avoid_empty_else: true
    # 불필요한 this 금지
    unnecessary_this: true
    # 불필요한 new 금지
    unnecessary_new: true

    # === 가독성 ===
    # 한 줄에 하나의 선언
    avoid_multiple_declarations_per_line: true
    # 빈 생성자 본문 금지
    empty_constructor_bodies: true

    # === Riverpod 관련 ===
    # Provider를 외부에서 변경하지 않도록
    # (riverpod_lint 추가 시 더 많은 규칙 적용 가능)
