targets:
  $default:
    builders:
      # freezed 설정
      freezed:
        options:
          # copyWith 메서드 생성
          copy_with: true
          # == 연산자 생성
          equal: true
          # toString 메서드 생성 (디버깅용)
          to_string: true
          # fromJson/toJson 생성 (json_serializable 사용 시)
          from_json: true
          to_json: true

      # json_serializable 설정
      json_serializable:
        options:
          # 명시적으로 지정된 필드만 JSON에 포함
          explicit_to_json: true
          # 알 수 없는 키 무시 (API 응답이 변경되어도 에러 안 남)
          checked: false
          # 필드 이름 자동 변환 (camelCase ↔ snake_case)
          field_rename: snake

      # riverpod_generator 설정
      riverpod_generator:
        options:
          # Provider 이름에 자동으로 'Provider' 접미사 추가
          provider_name_prefix: ""
